site_name: OpenML Docs
repo_url: https://github.com/openml/docs/
repo_name: 'openml/docs'
edit_uri: edit/master/docs/
site_url: https://docs.openml.org/
theme:
    name: "material"
    language: "en"
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - content.code.copy
        - content.action.edit
        - content.action.view
    palette:
        # Light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          accent: indigo
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
        # Dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: indigo
          accent: indigo
          scheme: slate
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    font:
        text: "Roboto"
        code: "Roboto Mono"
    logo: img/openml.png
    icon:
        edit: material/pencil 
        view: material/eye
markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.tabbed:
        alternate_style: true
    - admonition
    - toc:
        permalink: true
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
        anchor_linenums: true

plugins:
    - multirepo:
        cleanup: false
    - autorefs
    - section-index
    #- awesome-pages
    - mkdocs-jupyter:
        remove_tag_config:
            remove_input_tags:
                - hide_code
    - redirects:
        redirect_maps:
            'APIs.md': 'https://www.openml.org/apis'
            'REST-API.md': 'https://www.openml.org/apis'
    - search:
        separator: '[\s\-\.]+'
        lang:
            - en
    #- mkdocstrings:
    #    handlers:
    #        python:
    #        options:
    #            docstring_style: numpy
    #- gen-files:
    #    scripts:
    #        - scripts/gen_ref_pages.py
    #- literate-nav:
    #    nav_file: SUMMARY.md
nav:
    - OpenML:
        - Introduction: index.md
        - Getting Started: integrations/getting_started.ipynb
        - Concepts:
            - Main concepts: concepts/index.md
            - Data: concepts/data.md
            - Tasks: concepts/tasks.md
            - Flows: concepts/flows.md
            - Runs: concepts/runs.md
            - Collections: concepts/benchmarking.md
            - Tagging: concepts/tagging.md
            - Openness: concepts/openness.md
            - Sharing: concepts/sharing.md
        - Governance: Governance.md
    - Showcase:
        - "Code": showcase/index.md
        - Research: showcase/research.md
    - Benchmarking:
        - Benchmarking Suites: benchmark.md
        - AutoML Benchmark:
            - "AutoML Benchmark": automl/AutoML-Benchmark.md
            - "Important Parameters": automl/important_params.md
            - Tutorials:
                - "Basic Example - Random Forest": automl/basic_example.md
                - "Specific Task and Fold": automl/specific_task_fold_example.md
    - Contributing:
        - "How to Contribute": contributing/Contributing.md
        - "Documenting": contributing/OpenML-Docs.md
        - "Visual Guidelines": contributing/Visual-Guidelines.md
        - "Website":
            - "Getting started": contributing/website/Website.md
            - "Flask backend": contributing/website/Flask.md
            - "React frontend": contributing/website/React.md
            - "Dash visualizations": contributing/website/Dash.md
        - "Backend":
            - "Local Installation": contributing/backend/Local-Installation.md
            - "API Development": contributing/backend/API-development.md
            - "Evaluation Engine": contributing/backend/Java-App.md
        - "OpenML Definition": contributing/OpenML_definition.md
        - "Client Development": contributing/Client-API-Standards.md
        - "Datasets": contributing/Datasets.md
        - "Resources": contributing/resources.md
        - "Terms" : contributing/terms.md
    #- Python: '!import https://github.com/openml/openml-python?branch=docs/mkdoc'
    - PyTorch: '!import https://github.com/openml/openml-pytorch'
    - Julia: '!import https://github.com/openml/OpenML.jl?branch=dev&docs_dir=docs/build'
    - Ecosystem:
        - Python Integrations:
            - Scikit-learn:
                - "Introduction": integrations/Scikit-learn/index.md
                - Tutorials:
                    - "Basic tutorial": integrations/Scikit-learn/basic_tutorial.ipynb
                    - "Loading a dataset": integrations/Scikit-learn/datasets_tutorial.ipynb
            - Pytorch:
                - "Introduction" : integrations/Pytorch/index.md
                - Tutorials:
                    - "Basic Example": integrations/Pytorch/basic_tutorial.ipynb
            - "Tensorflow": Tensorflow.md
            - "Keras": Keras.md
        - R Integrations:
            - "MLR": integrations/mlr.md
        - Julia Integrations:
            - "Flux": integrations/Julia.md
        - Other Integrations:
            - "Weka": integrations/Weka.md
            - "MOA": integrations/MOA.md
            - "Java": integrations/Java.md
            - "REST API": integrations/Rest.md
        - Developer Guide:
            - "Creating a new integration": integrations/creating_extensions.md
extra_css:
    - css/extra.css
extra_javascript:
    - js/extra.js
