version: 2

jobs:
  deploydocs:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Deploy
          command: mkdocs gh-deploy -m "Deployment of commit {sha} [ci skip]"
      - run:
          name: Deploy2
          command: mkdocs gh-deploy -m "Deployment of commit {sha} [ci skip]"


workflows:
  version: 2
  build:
    jobs:
      - deploydocs:
          filters:
            branches:
              only:
                - master
